Application logic creation
romatoom/test-guru pull request #8
Opened 2022-08-10 15:39 UTC by romatoom

2022-08-10 16:34 UTC, BubuntuClu requested changes

2022-08-10 16:34 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    def author
это уже лишний метод, так как есть `set_user`

2022-08-10 16:34 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +      t_params[:author_id] = @test.nil? ? author.id : @test.author.id
это надо задавать через ассоциацию, а не через правку параметров

2022-08-10 16:34 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +  def boolean_to_yes_no(bool)
thinking face

2022-08-10 16:34 UTC, BubuntuClu commented on app/helpers/users_tests_helper.rb
> +  def test_passed?(result_in_percent)
это метод модели

2022-08-10 16:34 UTC, BubuntuClu commented on app/helpers/users_tests_helper.rb
> +    result = (user_test.correct_answers.to_f / user_test.questions_count * 100).round
это метод модели

2022-08-10 16:34 UTC, BubuntuClu commented on app/helpers/users_tests_helper.rb
> +    if test_passed?(result)
`if test_passage.success?`

2022-08-10 16:34 UTC, BubuntuClu commented on app/helpers/users_tests_helper.rb
> +    result_in_percent >= 85
85 - магическое число. надо вынести в константу в модели и обозвать ее понятно

2022-08-10 16:34 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :users, through: :users_tests, dependent: :destroy
при удалении теста, ты хочешь удалить всех пользователей которые проходили этот тест?

видимо, из-за таких как ты сделали ограничение на `dependent`опцию для ассоциаций построенных через `through`. опция не работает.

нельзя бездумно ко всему применять удаление или что-то еще. не всегда тебя разработчики fremework'a защитить смогут

2022-08-10 16:34 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests, through: :users_tests, dependent: :destroy
и тут тоже

2022-08-10 16:34 UTC, BubuntuClu commented on app/models/users_test.rb
> +  before_validation :before_validation_set_first_question, on: :create
сможешь в один метод объединить выставление первого вопроса и след вопроса?
чтобы метод сам решал что надо сделать

2022-08-11 05:40 UTC, romatoom commented on app/models/test.rb
> +  has_many :users, through: :users_tests, dependent: :destroy
:-(

2022-08-11 08:45 UTC, merged